sudo: false

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

# Installed for linting the project
language: node_js
node_js: "6"

install: true

script: ./scripts/build-package

branches:
  only:
    - master

git:
  depth: 10
